//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_FinalProject
{


    public partial class Default
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Group8_FinalProject.Site1 Master
        {
            get
            {
                return ((Group8_FinalProject.Site1)(base.Master));
            }
        }
    }
}
